<?php
/**
 * @file
 * gnl_schema.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function gnl_schema_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'Transparency',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'd818c8c5-88b2-4e64-987e-9e4cedae7f77',
  'type' => 'page',
  'language' => 'und',
  'created' => 1375230550,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '22c6d32e-d297-46d0-8050-95c9d49ef1ca',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Our goal is to make this project as transparent as possible. To that end, we\'re committed to sharing as many details as possible. Please peruse our project\'s planning and documentation:</p>
        <ul>
          <li><a href="https://drive.google.com/#folders/0B9y9maMoYSDFTTdGSWdBemZWUGM">Our Google Drive documents</a></li>
          <li><a href="https://trello.com/board/detroit-ledger-sprints/51ad360e37bb425f76000cf7">Our todo list</a></li>
          <li><a href="https://github.com/detroitledger">Github</a></li>
        </ul>

<h2>Our mistakes</h2>

<p>The nonprofit <a href="http://www.givewell.org/about/shortcomings">GiveWell</a> shares "mistakes we\'ve made, strategies we should have planned and executed differently, and lessons we\'ve learned." We\'ll do the same here.</p>

<p>Website timing issues</p>

<p>Fundraising campaign</p>',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Our goal is to make this project as transparent as possible. To that end, we\'re committed to sharing as many details as possible. Please peruse our project\'s planning and documentation:</p>
<ul><li><a href="https://drive.google.com/#folders/0B9y9maMoYSDFTTdGSWdBemZWUGM">Our Google Drive documents</a></li>
<li><a href="https://trello.com/board/detroit-ledger-sprints/51ad360e37bb425f76000cf7">Our todo list</a></li>
<li><a href="https://github.com/detroitledger">Github</a></li>
</ul><p>Our mistakes</p>
<p>The nonprofit <a href="http://www.givewell.org/about/shortcomings">GiveWell</a> shares "mistakes we\'ve made, strategies we should have planned and executed differently, and lessons we\'ve learned." We\'ll do the same here.</p>
<p>Website timing issues</p>
<p>Fundraising campaign</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2013-07-30 20:29:10 -0400',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'About the Detroit Ledger',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '66b512a5-e5dc-4a0f-ad40-ea86f955c028',
  'type' => 'page',
  'language' => 'und',
  'created' => 1375229535,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7ea570ba-598c-436c-9c7b-29e7e974f14b',
  'revision_uid' => 0,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'We\'re building  a picture of philanthropy in Detroit. We’re keeping track of grants and loans given to organizations in the city of Detroit, focusing on non-profits and civic projects that receive money from foundations, and need your help to get to the next level.

There’s a lot of talk about the reach and impact of nonprofits and foundations in Detroit. We find ourselves curious about how much money comes into the city and how it is used. We see many amazing non-profit organizations doing great work and want to show how they put resources to good use.

For all of the good work that organizations are doing in Detroit, much of it happens sight unseen. It’s difficult for nonprofits, residents, and scholars to see the bigger picture of the funding system they inhabit. Some funders do a great job of listing their grants online, but many don’t. Some non-profit organizations post annual reports online, but the digital divide can make this task difficult and expensive.

We’ve built a spreadsheet that lists close to 300 grants made in Detroit in the last year or so. It’s been a valuable resource, but it’s time to take the next step.

This summer, we\'re expanding the data and making it easy for everyone to access. As technologists in Detroit, we will build an awesome website to showcase grants and funders. All the data will be available for free, online, in bulk, under a copyright-free license.

But to get a comprehensive dataset, we need someone dedicated to getting the information. That’s why we’re sponsoring an internship. Here\'s where the funding will go: entirely to an intern\'s summer stipend.

<h2>Who we are</h2>

<h3>Matt Hampel</h3>

<p>"In 2012, I worked through Code for America with the City of Detroit to help build TextMyBus, a real-time bus arrival system for Detroit. My company, LocalData, is making tech tools for neighborhood organizations that allow groups to quickly collect and map important information. I’ve previously worked on technology projects at the University of Michigan and Chicago Tribune, among other places."</p>

<h3>Benjamin Chodoroff</h3>

<p>"I am a programmer who works with various free software projects. I co-own a small design/dev firm, http://theworkdept.com - we build websites and database-driven applications. Ever since highschool, I’ve been a technology activist. I am an advising member of the Detroit Digital Justice Coalition and help neighborhoods build wireless networks."</p>

<h3>Jessica McInchak</h3>

<p>“I am a recent graduate in urban sociology and do a lot of my thinking at the intersections of place-making, open-data, and spatial justice.  So far, this has all made for a creative niche where I get to work doing data-inspired, community-focused projects, just like this one.  In past years, I’ve interned with National Neighborhood Indicator Partners in Detroit and Chicago.”</p>

',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>We\'re building  a picture of philanthropy in Detroit. We’re keeping track of grants and loans given to organizations in the city of Detroit, focusing on non-profits and civic projects that receive money from foundations, and need your help to get to the next level.</p>
<p>There’s a lot of talk about the reach and impact of nonprofits and foundations in Detroit. We find ourselves curious about how much money comes into the city and how it is used. We see many amazing non-profit organizations doing great work and want to show how they put resources to good use.</p>
<p>For all of the good work that organizations are doing in Detroit, much of it happens sight unseen. It’s difficult for nonprofits, residents, and scholars to see the bigger picture of the funding system they inhabit. Some funders do a great job of listing their grants online, but many don’t. Some non-profit organizations post annual reports online, but the digital divide can make this task difficult and expensive.</p>
<p>We’ve built a spreadsheet that lists close to 300 grants made in Detroit in the last year or so. It’s been a valuable resource, but it’s time to take the next step.</p>
<p>This summer, we\'re expanding the data and making it easy for everyone to access. As technologists in Detroit, we will build an awesome website to showcase grants and funders. All the data will be available for free, online, in bulk, under a copyright-free license.</p>
<p>But to get a comprehensive dataset, we need someone dedicated to getting the information. That’s why we’re sponsoring an internship. Here\'s where the funding will go: entirely to an intern\'s summer stipend.</p>
<p>Who we are</p>
<p>Matt Hampel</p>
<p>"In 2012, I worked through Code for America with the City of Detroit to help build TextMyBus, a real-time bus arrival system for Detroit. My company, LocalData, is making tech tools for neighborhood organizations that allow groups to quickly collect and map important information. I’ve previously worked on technology projects at the University of Michigan and Chicago Tribune, among other places."</p>
<p>Benjamin Chodoroff</p>
<p>"I am a programmer who works with various free software projects. I co-own a small design/dev firm, <a href="http://theworkdept.com">http://theworkdept.com</a> - we build websites and database-driven applications. Ever since highschool, I’ve been a technology activist. I am an advising member of the Detroit Digital Justice Coalition and help neighborhoods build wireless networks."</p>
<p>Jessica McInchak</p>
<p>“I am a recent graduate in urban sociology and do a lot of my thinking at the intersections of place-making, open-data, and spatial justice.  So far, this has all made for a creative niche where I get to work doing data-inspired, community-focused projects, just like this one.  In past years, I’ve interned with National Neighborhood Indicator Partners in Detroit and Chicago.”</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2013-07-30 20:12:15 -0400',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Our Methods',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'baa55cf9-698b-4b40-8623-4f0cc03dd2ab',
  'type' => 'page',
  'language' => 'und',
  'created' => 1375230230,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd0766f2c-35c8-4338-b8fc-28cee03b2dd5',
  'revision_uid' => 0,
  'body' => array(),
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2013-07-30 20:23:50 -0400',
);
  return $nodes;
}
