<?php
/**
 * @file
 * Code for the gnl_schema feature.
 */

include_once 'gnl_schema.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gnl_schema_form_grant_node_form_alter(&$form, &$form_state) {
  $form['title']['#required'] = FALSE;
  $form['title']['#type'] = 'hidden';
}

/**
 * Implements hook_entity_info_alter().
 *
 * Add view modes.
 */
function gnl_schema_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['grantor_only'] = array(
    'label' => t('Grantor only'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['grantee_only'] = array(
    'label' => t('Grantee only'),
    'custom settings' => FALSE,
  );
}

/**
* Implements hook_preprocess_node().
*
* Add template hints for the added view modes
*/
function gnl_schema_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'grantor_only') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__grantor_only';
  }
  if($vars['view_mode'] == 'grantee_only') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__grantee_only';
  }
}

